# Generated by Django 5.2.12 on 2026-03-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_rate', models.FloatField()),
                ('rpm', models.IntegerField()),
                ('water_conc', models.FloatField()),
                ('acetone_conc', models.FloatField()),
                ('reynolds', models.FloatField()),
                ('efficiency', models.FloatField()),
            ],
        ),
    ]
